LANG =
	version: 'Version ' + CONFIG.version
	welcome: 'Welcome to the unofficial scene editor of My Candy Love! A tool created with Love by <a href="https://tumblr.com/follow/lucasmciruzzi" target="_blank">Lucas</a> and <a href="https://tumblr.com/follow/myasaberhagen" target="_blank">Mya</a>. We hope you have fun! You can publish your creations under the tag <a href="https://tumblr.com/tagged/mcleditor">#mcleditor</a>.'
	legal: 'All images belong to <a href="http://beemoov.com" target="_blank">Beemoov</a>'
	account: 'Account'
	region: 'Region'
	username: 'Name'
	username_placeholder: 'Username (NOT your e-mail)'
	change_avatar: 'Load Avatar'
	love_level: 'Love Level'
	chat: 'Dialogue'
	characters_bubble_label: 'Dialogue bubble'
	characters_bubble: 'Dialogue bubble'
	answers_label: 'Answers'
	answers: 'Answers (ENTER to separate)'
	scene: 'Place'
	characters: 'Characters'
	avatar: 'Avatar'
	character: 'Character'
	language: 'Language'
	view_result: 'Ver Result'
	use_sucrette: 'Use File'
